name: squadron_builder
description: Dart code generator for Squadron workers. Implement your worker service and let squadron_builder bridge the gap with Web Workers and Isolates!
version: 8.3.0
homepage: https://github.com/d-markey/squadron_builder
repository: https://github.com/d-markey/squadron_builder

environment:
  sdk: ^3.7.0

platforms:
  linux:
  windows:
  macos:

dependencies:
  squadron: ^7.3.0
  build: ^4.0.0
  source_gen: ^4.0.0
  analyzer: ^8.0.0
  dart_style:
  pub_semver:
  meta:

dev_dependencies:
  lints: ">=4.0.0"
  test:
  build_runner:
  build_test:
  source_gen_test:
  logger:
  cancelation_token:
  using:
  freezed:
  freezed_annotation:
  path: ^1.9.1
  yaml: ^3.1.3

dependency_overrides:
  source_gen_test:
    git:
      url: https://github.com/d-markey/source_gen_test
      ref: generateForLibrary

topics:
  - concurrency
  - parallelism
  - isolate
  - multithread
  - web-worker

funding:
  - https://github.com/sponsors/d-markey
  - https://buymeacoffee.com/dmarkey
